from pathlib import Path
from typing import Optional
from ..domain.models import MergeResult, MergeStatistics


class MergeReporter:

    @staticmethod
    def generate_report(result: MergeResult, output_path: Optional[Path] = None) -> str:
        report_lines = []
        report_lines.append("# SPDX SBOM Merge Report\n")
        report_lines.append(
            f"**Generated:** {result.merged_document.creation_info.get('created', 'Unknown')}\n"
        )
        report_lines.append("---\n")

        report_lines.append("## Merge Statistics\n")
        stats = result.statistics
        report_lines.append(
            f"- **Total SBOMs Processed:** {stats.total_sboms_processed}"
        )
        report_lines.append(f"- **Root Packages:** {stats.root_packages_count}")
        report_lines.append(
            f"- **Dependency Packages:** {stats.dependency_packages_count}"
        )
        report_lines.append(
            f"- **Total Packages in Merged SBOM:** {stats.total_packages}"
        )
        report_lines.append(
            f"- **Duplicate Packages Removed:** {stats.duplicate_packages_removed}"
        )
        report_lines.append(f"- **Total Relationships:** {stats.total_relationships}")
        report_lines.append(
            f"- **Processing Time:** {stats.processing_time_seconds:.2f} seconds\n"
        )

        report_lines.append("---\n")

        report_lines.append("## Validation Results\n")

        if not stats.validation_errors and not stats.validation_warnings:
            report_lines.append("✅ **No validation issues found**\n")
        else:
            if stats.validation_errors:
                report_lines.append(f"### ❌ Errors ({len(stats.validation_errors)})\n")
                for error in stats.validation_errors:
                    report_lines.append(f"- {error}")
                report_lines.append("")

            if stats.validation_warnings:
                report_lines.append(
                    f"### ⚠️ Warnings ({len(stats.validation_warnings)})\n"
                )
                for warning in stats.validation_warnings:
                    report_lines.append(f"- {warning}")
                report_lines.append("")

        report_lines.append("---\n")

        report_lines.append("## Merged Document Details\n")
        report_lines.append(
            f"- **SPDX Version:** {result.merged_document.spdx_version}"
        )
        report_lines.append(f"- **Document Name:** {result.merged_document.name}")
        report_lines.append(
            f"- **Document Namespace:** {result.merged_document.document_namespace}"
        )
        report_lines.append(
            f"- **Data License:** {result.merged_document.data_license}\n"
        )

        if result.merged_document.comment:
            report_lines.append("### Comment")
            report_lines.append(f"{result.merged_document.comment}\n")

        report_lines.append("---\n")

        report_lines.append("## Package Sources\n")
        source_counts = {}
        for pkg in result.merged_document.packages:
            source = pkg.source_sbom or "Unknown"
            source_counts[source] = source_counts.get(source, 0) + 1

        for source, count in sorted(source_counts.items()):
            report_lines.append(f"- **{source}:** {count} packages")

        report_lines.append("\n---\n")
        report_lines.append("*Report generated by merge-spdx-sboms v1.0.0*\n")

        report_content = "\n".join(report_lines)

        if output_path:
            report_path = output_path.parent / f"{output_path.stem}_merge_report.md"
            with open(report_path, "w", encoding="utf-8") as f:
                f.write(report_content)

        return report_content
